---
kind: pipeline
type: docker
name: default

steps:
- name: install and run scripts
  image: python:3.8
  commands:
  - git fetch --tags
  - python setup.py install
  - python scripts/dessia_object.py
  - python dessia_common/scripts/unit_tests.py

- name: develop
  image: python:3.8
  commands:
  - python setup.py develop

- name: generate sdist
  image: python:3.8
  commands:
  - git fetch --tags
  - python setup.py sdist

- name: notify
  when:
    status:
    - failure
  image: drillster/drone-email
  settings:
    host: mail.dessia.tech
    username: technical@dessia.tech
    password:
     from_secret: email_password
    from: technical@dessia.tech
    recipients: [ root@dessia.tech ]
