---
kind: pipeline
type: docker
name: default

steps:
- name: merge master on testing
  image: alpine/git
  when:
    event: push
    branch: master
  commands:
  - git fetch origin testing
  - git checkout testing
  - git merge master
  - git push

- name: merge testing on dev
  image: alpine/git
  when:
    event: push
    branch: testing
  commands:
  - git fetch origin dev
  - git checkout dev
  - git merge testing
  - git push

- name: notify
  when:
    status:
    - failure
  image: drillster/drone-email
  settings:
    host: mail.dessia.tech
    username: technical@dessia.tech
    password:
     from_secret: email_password
    from: technical@dessia.tech

- name: check code complexity, docs & code quality
  image: dessia/python-ci:3.9
  commands:
  - pip install pydocstyle==6.3.0 pylint==2.16.1 pyenchant==3.2.2
  - python code_pylint.py
  - python code_pydocstyle.py

  volumes:
    # Mount pip cache from host
    - name: pip_cache
      path: /root/.cache/pip

- name: check pep8 formatting
  image: python:3.9
  commands:
    - git fetch --tags
    - pip3 install -U pip autopep8
    - bash code_pep8.sh

  volumes:
    # Mount pip cache from host
    - name: pip_cache
      path: /root/.cache/pip

- name: check changelog update
  image: python:3.9
  when:
    event: pull_request
    branch:
      - master
      - dev
  commands:
    - bash code_changelog.sh


- name: install, run scripts and build doc
  image: python:3.9
  commands:
  - git fetch --tags
  - pip install .
  - pip install sphinx sphinx-rtd-theme coverage volmdlr==0.12.0 nbformat nbconvert
  - pip install plot_data --no-cache-dir
  - pip show coverage
  - pip show plot_data
  - cd doc
  - make html
  - cd ../tests
  - coverage run --source dessia_common ci_tests.py
  - cd ../test_unittests
  - coverage run --source dessia_common -m unittest discover -v
  - cd ../tutorials
  - coverage run --source dessia_common ci_tutorials.py
  - cd ..
  - coverage combine tests/.coverage test_unittests/.coverage tutorials/.coverage
  - coverage json
  - coverage report
  - coverage html
  - python coverage.py

  volumes:
    # Mount pip cache from host
    - name: pip_cache
      path: /root/.cache/pip

- name: develop
  image: python:3.9
  commands:
  - python setup.py develop

  volumes:
    # Mount pip cache from host
    - name: pip_cache
      path: /root/.cache/pip


- name: generate sdist
  image: python:3.9
  when:
      branch: master

  commands:
  - git fetch --tags
  - python setup.py sdist

  volumes:
    # Mount pip cache from host
    - name: pip_cache
      path: /root/.cache/pip


- name: upload to pypi
  image: plugins/pypi
  when:
      event: tag
  settings:
    skip_build: True
    username: dessia_tech
    password:
        from_secret: pypi_password

- name: upload_doc_master
  image: appleboy/drone-scp
  when:
    event: push
    branch: master
  settings:
    host: austerlitz.dessia.tech
    target: /var/www/documentation/dessia_common/
    source: doc/build/html/*
    strip_components: 3
    username: drone
    password:
      from_secret: ssh_drone_password

- name: upload coverage
  image: appleboy/drone-scp
  when:
    event: push
  settings:
    host: magenta.dessia.tech
    target: /var/www/cdn/dessia_common/coverage/${DRONE_BRANCH}
    source: htmlcov/*
    strip_components: 1
    username: drone
    password:
      from_secret: ssh_drone_password

volumes:
  - name: pip_cache
    host:
      path: /tmp/cache/drone/pip
