kind: pipeline
name: default

steps:
- name: install
  image: python:3
  commands:
  - git fetch --tags
  - python setup.py install

- name: develop
  image: python:3
  commands:
  - python setup.py develop

- name: generate sdist
  image: python:3
  commands:
  - git fetch --tags
  - python setup.py sdist --formats=gztar,zip

- name: push opensource from sdist
  image: alpine/git
  when:
    branch: 
      - master
  commands:
    - git clone https://git.dessia.tech/OpenSource/dessia_common.git git-opensource
    - tar -vxf dist/*.tar.gz --strip-components=1 -C git-opensource
    - cd git-opensource
    - git config --global user.email "root@dessia.tech"
    - git config --global user.name "Root commit bot" 
    - git add -A
    - if ! [[ -z $(git status -s -uno) ]]; then git commit -m "Automated commit from "${DRONE_COMMIT_MESSAGE##\"%%\\n\"}; fi
    - git push origin master

- name: upload sdist to seafile
  image: dessia/drone-seafile
  when:
    branch: master
  settings:
    server_url: https://partage.dessia.tech
    repo_id:
      from_secret: seafile_repo_id
    seafile_token:
      from_secret: seafile_token
    files: dist/*
    root_directory: /dessia-common/

- name: notify
  when:
    status:
    - failure 
  image: drillster/drone-email
  settings:
    host: mail.dessia.tech
    username: software@dessia.tech
    password:
     from_secret: email_password
    from: software@dessia.tech
    recipients: [ root@dessia.tech ]
