---
kind: pipeline
type: docker
name: default

steps:
- name: install and run scripts
  image: python:3.8
  commands:
  - git fetch --tags
  - python setup.py install
  - python scripts/dessia_object.py
  - python dessia_common/scripts/unit_tests.py

- name: develop
  image: python:3.8
  commands:
  - python setup.py develop

- name: generate sdist
  image: python:3.8
  commands:
  - git fetch --tags
  - python setup.py sdist

- name: compile linux test licence valid
  image: python:3.8
  commands:
  - pip install Cython netifaces
  - python compile.py cdist_wheel --exp-month=7 --exp-year=2029 --detect-macs
  - pip install client_dist/*.whl
  - python scripts/compilation_test.py test_valid_license

- name: compile linux test licence unvalid
  image: python:3.8
  commands:
  - pip install Cython netifaces
  - python compile.py cdist_wheel --exp-month=7 --exp-year=2029 --macs=222222222122
  - pip install client_dist/*.whl
  - python scripts/compilation_test.py test_unvalid_license


- name: push opensource from sdist
  image: alpine/git
  when:
    branch: 
    - master
    event: 
    - push
  commands:
  - git clone https://gitea.dessia.tech/OpenSource/dessia-common.git git-opensource
  - cd git-opensource
  - git branch from_proprietary
  - git checkout from_proprietary
  - git pull origin from_proprietary
  - git config --global user.email "root@dessia.tech"
  - git config --global user.name "Root commit bot"
  - tar -vxf ../dist/*.tar.gz --strip-components=1 -C .
  - git add -A
  - if ! [[ -z $(git status -s -uno) ]]; then git commit -m "Automated commit from dessia common proprietary repo"; fi
  - git push origin from_proprietary

- name: copy tag to opensource
  image: alpine/git
  when:
    event:
    - tag
  commands:
  - git clone https://gitea.dessia.tech/OpenSource/dessia-common.git git-opensource
  - cd git-opensource
  - git branch from_proprietary
  - git checkout from_proprietary
  - git pull origin from_proprietary
  - git config --global user.email "root@dessia.tech"
  - git config --global user.name "Root commit bot"
  - git tag -a ${DRONE_TAG} -m ${DRONE_TAG}
  - git push origin --tags


- name: upload sdist to seafile
  image: dessia/drone-seafile
  when:
    branch:
    - master
    event: 
    - push
  settings:
    server_url: https://partage.dessia.tech
    repo_id:
      from_secret: seafile_repo_id
    seafile_token:
      from_secret: seafile_token
    files: dist/*
    root_directory: /dessia-common/

- name: notify
  when:
    status:
    - failure
  image: drillster/drone-email
  settings:
    host: mail.dessia.tech
    username: technical@dessia.tech
    password:
     from_secret: email_password
    from: technical@dessia.tech
    recipients: [ root@dessia.tech ]
