---
kind: pipeline
type: docker
name: default

steps:
- name: install and run scripts
  image: python:3
  commands:
  - git fetch --tags
  - python setup.py install
  - python scripts/dessia_object.py

- name: develop
  image: python:3
  commands:
  - python setup.py develop

- name: generate sdist
  image: python:3
  commands:
  - git fetch --tags
  - python setup.py sdist

- name: push opensource from sdist
  image: alpine/git
  when:
    branch: 
    - master
    event:
    - push
  commands:
  - git clone https://gitea.dessia.tech/OpenSource/dessia-common.git git-opensource
  - cd git-opensource
  - git branch from_proprietary
  - git checkout from_proprietary
  - git pull origin from_proprietary
  - git config --global user.email "root@dessia.tech"
  - git config --global user.name "Root commit bot"
  - tar -vxf ../dist/*.tar.gz --strip-components=1 -C .
  - git add -A
  - echo ${DRONE_COMMIT_MESSAGE##\"%%\\n\"}
  - if ! [[ -z $(git status -s -uno) ]]; then git commit -m "Automated commit from "${DRONE_COMMIT_MESSAGE##\"%%\\n\"}; fi
  - git push origin from_proprietary

- name: upload sdist to seafile
  image: dessia/drone-seafile
  when:
    branch: master
    event: push
  settings:
    server_url: https://partage.dessia.tech
    repo_id:
      from_secret: seafile_repo_id
    seafile_token:
      from_secret: seafile_token
    files: dist/*
    root_directory: /dessia-common/

- name: notify
  when:
    status:
    - failure 
  image: drillster/drone-email
  settings:
    host: mail.dessia.tech
    username: technical@dessia.tech
    password:
     from_secret: email_password
    from: technical@dessia.tech
    recipients: [ root@dessia.tech ]
