---
kind: pipeline
type: docker
name: default

steps:
- name: check code complexity
  image: python:3.9
  commands:
  - pip install radon
  - ./code_quality.sh

- name: check pep8 formatting
  image: python:3.9
  when:
    branch: master
  commands:
    - git fetch --tags
    - pip3 install -U pip autopep8
    - bash pre-push
        
- name: install, run scripts and build doc
  image: python:3.8
  commands:
  - git fetch --tags
  - python setup.py install
  - python scripts/dessia_object.py
  - pip install sphinx sphinx-rtd-theme coverage plot-data
  - cd doc
  - make html
  - cd ../tests
  - coverage run --source dessia_common ci_tests.py
  - coverage json
  - python coverage.py 
  - coverage report

- name: develop
  image: python:3.8
  commands:
  - python setup.py develop

- name: generate sdist
  image: python:3.8
  commands:
  - git fetch --tags
  - python setup.py sdist


- name: upload to pypi
  image: plugins/pypi
  when:
      event: tag
  settings:
    skip_build: True
    username: dessia_tech
    password:
        from_secret: pypi_password

- name: upload_doc_master
  image: appleboy/drone-scp
  when:
    event: push 
    branch: master
  settings:
    host: austerlitz.dessia.tech
    target: /var/www/documentation/dessia_common/
    source: doc/build/html/*
    strip_components: 3
    username: drone
    password:
      from_secret: ssh_drone_password

- name: notify
  when:
    status:
    - failure
  image: drillster/drone-email
  settings:
    host: mail.dessia.tech
    username: technical@dessia.tech
    password:
     from_secret: email_password
    from: technical@dessia.tech
